MisSoluciones/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf.urls import url
from Soluciones.views import *
from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index,name='index'),
    path('problema/<str:libro>', problema,name='problema'),
    path('cargar', cargar, name="cargar"), #OK
    path('contac/', contac, name="contac"), #OK
    path('formaPKT/', formaPket, name="formaPket"), #OK
    path('error/', Tuerror, name="Tuerror"), #OK
    path('versolucion/<str:libro>/<str:numero>', versolucion,name='versolucion'), #OK


    path('login/', Milogin, name="Milogin"), #OK
    path('logout/', logout, name="logout"), #OK
    path('registrarse/', registro, name="registro"), #OK
    path('', index, name="index"), #OK
    path('ajax/compraPKT/', compraPKT, name='compraPKT'), #OK
    path('tematicas_actualizar/<slug:pk>', TematicasAct.as_view(),name='TematicasAct'), #OK
    path('tematicas_list', Tematicas.as_view(),name='listatemas'), #OK
    path('tematicas_form/', CreaTemas.as_view(), name='Createmas'), #OK
    path('borra_temas/<slug:pk>', BorraTemas.as_view(template_name='temas_confirm_delete.html'),name='borraTemas'), #OK
    path('libros_actualizar/<slug:pk>', librosAct.as_view(),name='librosAct'), #OK
    path('libros_list', ListaLibros.as_view(),name='listalibros'), #OK
    path('borra_libros/<slug:pk>', BorraLibro.as_view(template_name='libros_confirm_delete.html'),name='borralibros'), #OK
    path('libros_form/', CreaLibro.as_view(), name='CreaLibro'), #OK
    path('ajax/getProblemas/', getProblemas, name='getProblemas'),
    path('ajax/enviacorreoValidar/', enviacorreoValidar, name='enviacorreoValidar'),
    path('verPaquetes/<str:codigo>', verPaquetes,name="verPaquetes"), #OK
    path('busquedas/', consultar,name="consultar"), #OK
    path('verMiPKT/<str:pkt>', mipkt,name="mipkt"), #OK
    path('ajax/borraPa/', borraPa, name='borraPa'),
    path('ajax/poblarPaquetes/', poblarPaquetes, name='poblarPaquetes'),
    path('ajax/borrarPaquetes/', borrarPaquetes, name='borrarPaquetes'),
    path('ajax/getPaquetes/', getPaquetes, name='getPaquetes'),
    path('ajax/BuscaTemasxLibros/', BuscaTemasxLibros, name='BuscaTemasxLibros'),
    path('ajax/BuscaProblemas/', BuscaProblemas, name='BuscaProblemas'),
    path('ajax/Muestraproblemas/', Muestraproblemas, name='Muestraproblemas'),
    path('ajax/getDetalles/', getDetalles, name='getDetalles'),
    path('ajax/TranferMovil/', TranferMovil, name='TranferMovil'),
    path('TranferMovil/<str:pkt>/<str:usuario>', TranferMovil, name='TranferMovil'),
    path('contactanos/', contactanos,name="contactanos"),
    path('terminos/', terminos, name="terminos"),
    path('team/', team,name="team"),
    path('ajax/creaCodigo/', Creacodigo, name='Creacodigo'),
    path('promociones/', promociones,name="promociones"),
    path('listaPaquetes/<str:miperfil>', LPaquetes, name='LPaquetes') #OK
    ]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Soluciones/models.py
from django.db import models
from django.contrib.auth.models import User

class perfil(models.Model):
    perfilID=models.AutoField(primary_key=True)
    nombrePerfil=models.CharField(max_length = 50)
    def __str__(self):
        return '%s'%(self.nombrePerfil)

class tematicas(models.Model):
    temaNombre=models.CharField(max_length=50, null=True,verbose_name='Nombre del Tema')
    perfilId=models.ForeignKey(perfil,on_delete=models.CASCADE,null=True,verbose_name='Perfil')
    agregadoPor = models.IntegerField(null=True)
    def __str__(self):
        return '%s'%(self.temaNombre)

class libros(models.Model):

    titulo=models.CharField(max_length = 50,null=True,verbose_name="Título" )
    autor=models.CharField(max_length = 50,null=True,verbose_name="Autor" )
    edicion=models.CharField(max_length = 50,null=True,verbose_name="Edición" )
    perfilId=models.ForeignKey(perfil,on_delete=models.CASCADE,null=True,verbose_name="Perfil" )
    def __str__(self):
        return self.titulo
class correoValidacion(models.Model):
    correo=models.EmailField()
    codigo=models.IntegerField()
    validado=models.BooleanField()

class comentarios(models.Model):
    comentario=models.TextField(max_length = 50)
    correo=models.EmailField()
    tipo=models.CharField(max_length = 50)
    usuario=models.ForeignKey(User, on_delete=models.CASCADE)
    nombre=models.CharField(null=True,max_length = 50)
    respuesta=models.TextField(null=True,max_length = 150)
    responsable=models.IntegerField(null=True)
class solucionadores(models.Model):
    solucionadorNombre=models.CharField(max_length = 50)
    solucionadorPais=models.CharField(max_length = 50)
    solucionadorID=models.AutoField(primary_key=True)
    solucionadorPais=models.CharField(null=True,max_length = 50)
    def __str__(self):
        return self.solucionadorNombre

class paquetes(models.Model):
    paqueteID=models.AutoField(primary_key=True)
    paqueteCod=models.CharField(max_length=50, null=True,verbose_name="Codigo del paquete")
    paqueteCant=models.IntegerField(null=True, verbose_name="Cantidad de problemas que contiene")
    paquetePrecio=models.IntegerField(null=True,verbose_name="Precio")
    paqueteDias=models.IntegerField(null=True,verbose_name="Dias que estará activo")
    paqueteDescr=models.CharField(max_length=50, null=True,verbose_name="Descripción")
    paquetePerfil=models.ForeignKey(perfil, on_delete=models.CASCADE,null=True,verbose_name="Perfil")
    paqueteFecha=models.DateField(auto_now_add=True,null=True)
    paqueteCreador=models.ForeignKey(User, on_delete=models.CASCADE,null=True)


    def __str__(self):
        return '%s'%(self.paqueteCod)

class soluciones(models.Model):
    problemaNumero=models.CharField(max_length=50, null=True,verbose_name="Numero del Problema")
    problemaProblema=models.ImageField(upload_to='problemas', null=True,verbose_name="Figura del problema")
    problemaID=models.AutoField(primary_key=True)
    problemaLibro=models.ForeignKey(libros, on_delete=models.CASCADE,null=True,verbose_name="Libro o Guia")
    problemaSolucion=models.FileField(upload_to='soluciones',null=True,verbose_name="Documento de solución")
    problemaVideo=models.FileField(upload_to='videos',null=True,verbose_name="Audio de explicación")
    problemaSolucionadoPor=models.ForeignKey(solucionadores, on_delete=models.CASCADE,null=True,verbose_name="Solucionado por")
    problemaTema=models.ForeignKey(tematicas, on_delete=models.CASCADE,null=True,verbose_name="Tema del problema")
    problemaFecha=models.DateField(auto_now_add=True,)
    def __str__(self):
        return '%s%s'%(self.problemaNumero,self.problemaProblema)

class UsuarioPaq(models.Model):
    usuario=models.IntegerField(null=True)
    fechaIni=models.DateField(blank=True, null=True)
    fechaPago=models.DateField(blank=True, null=True)
    paqueteMio=models.ForeignKey(paquetes,on_delete=models.CASCADE,null=True)
    activo=models.BooleanField(blank=True, null=True)
    vencido=models.BooleanField(blank=True, null=True,default=False)
    def __str__(self):
        return '%s%s'%(self.usuario,self.paqueteMio)

class ProblemaPaq(models.Model):
    problemaID= models.ForeignKey(soluciones,on_delete=models.CASCADE,null=True)
    paqueteID= models.ForeignKey(paquetes,on_delete=models.CASCADE,null=True)

class QRPago(models.Model):
    qr=models.ImageField(upload_to='qr', null=True)
    Nombre=models.CharField(max_length=50, null=True)
    foto=models.ImageField(upload_to='foto', null=True,blank=True)
    

	

templates/FormaPKT.html
{% extends "index.html" %}

{% block contenido %}
    <br>
<div  style="height: 20px" class="jumbotron">
<div style="margin-left:auto;margin-right: auto;">
  <h5>Bienvenido a la Gestión de Paquetes</h5>
  <p>El siguiente módulo está reservado solo para el grupo de desarrollo del sitio</p>
 </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">

                <div class="col-xs-4">
        <label for="paquetes">Paquetes disponibles:</label>
        <select class="form-control" id="paquetes" onchange="BuscaT()">
        {% for i in paquetes %}
        <option>{{i.paqueteCod}}</option>
        {% endfor %}
        </select>
<br>
    <button type="button" onclick="creaCodigo()" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Crear Paquete</button>
    <button type="button" onclick="borrarPaquetes()" class="btn btn-primary">Borrar Paquete</button>

    <div class="col-xs-4">
        <label for="libros">Selecione un Libro:</label>
        <select class="form-control" id="libros" onchange="BuscaT()">
            <option></option>
        {% for i in libros %}
        <option>{{i.titulo}}</option>
        {% endfor %}
        </select>
    <label for="temas">Selecione un Tema :</label>
    <select multiple class="form-control" id="temas" onclick="BuscaP()">

           </select>

    <label for="temas">Seleccione los Problemas que formararán parte del paquete:</label>
    <select multiple class="form-control" id="problemas">
           </select>
<br>
    <button type="button"   onclick="muestraproblemas()" data-toggle="modal" data-target="#myModalyy"  class="btn btn-primary">Vista Previa</button>
    <button type="button" onclick="poblarPaquetes()" class="btn btn-primary">Insertar Problemas</button>
 </div>
<div id="myModalyy" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
<div id="demo1" class="landing-categories owl-carousel"  data-ride="carousel">


  <!-- The slideshow -->


  <!-- Left and right controls -->


</div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>


            </div>
 <div class="col-xs-4">
 <div id="figuras" >
 </div>
 </div>
</div>
   </div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">

    <form method="POST" class="post-form">{% csrf_token %}
        {{ formularioPaquetes.as_ul }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>


            </div>


        </div>
    </div>
</div>





<script>
 function BuscaT(){
     var libro=$("#libros option:selected").val();
       $.ajax({
        url: '{% url "BuscaTemasxLibros" %}',
        data: {
          'libro': libro

        },
        dataType: 'json',
        success: function (data) {
            $("#temas").empty()
          for(var ii=0;ii<data.temas.length;ii++){
              $("#temas").append('<option value='+data.temas[ii]+'>'+data.temas[ii]+'</option>');
          }
	}

}
          )}


 </script>


<script>
 function BuscaP(){
     var libro=$("#libros option:selected").val();
     var temas=$("#temas option:selected").text();


       $.ajax({
        url: '{% url "BuscaProblemas" %}',
        data: {
          'libro': libro,
          'temas': temas
        },
        dataType: 'json',
        success: function (data) {

          for(var ii=0;ii<data.problemas.length;ii++){
              $("#problemas").append('<option value='+data.problemas[ii]+'>'+data.problemas[ii]+'</option>');
          }
	}

}
          )}
 </script>
    <script>
 function muestraproblemas(){

     var text = $("#problemas").val() || [];

       $.ajax({
        url: '{% url "Muestraproblemas" %}',
        data: {
          'problemas': text

        },
        dataType: 'json',
        success: function (data) {




          $('#demo1').empty()
          for(var ii=0;ii<data.temas.length;ii++){
            var img = document.createElement('img');
            img.src = data.temas[ii];
            var node1 = document.createElement("div");
            node1.setAttribute("class","item");
            var node2 = document.createElement("div");
            node2.setAttribute("class","card rounded-0 border-0 text-center");
            node2.appendChild(img);
            node1.appendChild(node2);

            $('#demo1').append(node1)
          }
	}

}
          )}


 </script>
     <script>
 function creaCodigo(){



       $.ajax({
        url: '{% url "Creacodigo" %}',
        data: {


        },
        dataType: 'json',
        success: function (data) {
                $("#id_paqueteCod").val(data.codigo)


	}

}
          )}


 </script>
<script>
function poblarPaquetes(){
        var problemas=$("#problemas").val() || [];
        var paquete=$("#paquetes").val() ;

       $.ajax({
        url: '{% url "poblarPaquetes" %}',
        data: {
            'problemas':problemas,
            'paquete':paquete,

        },
        dataType: 'json',
        success: function (data) {
               alert(data.t)


	}

}
          )}
 </script>
 <script>
    function borrarPaquetes(){

        var paquete=$("#paquetes").val() ;

       $.ajax({
        url: '{% url "borrarPaquetes" %}',
        data: {

            'paquete':paquete,

        },
        dataType: 'json',
        success: function (data) {
               $("#paquetes").empty()
               for(var ii=0;ii<data.listapaquetes.length;ii++){
              $("#paquetes").append('<option value='+data.listapaquetes[ii]+'>'+data.listapaquetes[ii]+'</option>');
          }


	}

}
          )}
 </script>
{% endblock %}

templates/busquedas.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block contenido %}
 <body>
 <!div  style="height: 20px" class="jumbotron">
     <div  style="height: 20px" class="jumbotron">
<div style="margin-left:auto;margin-right: auto;">
    <br>
  <h5>Bienvenido al repositorio de Soluciones</h5>

 </div>
</div>
 <div class="data-table-area mg-b-15">

<table id="table" data-toggle="table"  data-search="true" data-show-columns="true"                                         >
        <thead>
            <tr>
                <th data-field="numero" data-editable="true">Número</th>
                <th data-field="libro" data-editable="true">Libro</th>
                <th data-field="tema" data-editable="true">Tema</th>
                <th data-field="id" data-editable="true">Solucionado</th>

            </tr>
        </thead>
        <tbody>
            {% for u in data %}

            <tr>
                <td >{{ u.problemaNumero }}</td>
                <td >{{ u.problemaLibro }}</td>
                <td>{{ u.problemaTema }}</td>
                <td>{{ u.problemaSolucionadoPor }}</td>

            </tr>
            {% endfor %}

        </tbody>
        <tfoot>
            <tr>
                <th>Número</th>
                <th>Libro</th>
                <th>Tema</th>
                <th>Solucionado</th>
            </tr>
        </tfoot>
    </table>
</div>
 </body>
</html>
 {% endblock %}

templates/contactanos.html
{% extends "index.html" %}

{% block contenido %}
<div  style="height: 20px" class="jumbotron">
<div style="margin-left:auto;margin-right: auto;">
  <h5>Hola ¿en qué te podemos ayudar?</h5>
  <p>Escribe al grupo de Desarrollo de Nuestra Empresa</p>
 </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form method = "POST"  action="/contac/" multipart/form-data"> {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Nombre</label>
                            <input type="text" name="nombre" class="form-control" id="name" placeholder="Escriba su nombre de contacto" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Escriba su correo" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">
                                Opciones</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Seleccione su problemática:</option>
                                <option value="Sobre el Servicio">Sobre el Servicio</option>
                                <option value="Sugerencias">Sugerencias</option>
                                <option value="Funcionamiento Inadecuado">Funcionamiento Inadecuado</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Comentarios</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Tu comentario"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Enviar</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">

            <legend><span class="glyphicon glyphicon-globe"></span>Oficina Central</legend>
            <address>
                <strong>LA Habana, Cuba.</strong><br>
                75 114 Ave, Instituto Superior Politécnico(IPSJAE)<br>
                Marianao, No 94107<br>
                <address title=" Número Telefónico">
                    P:</abbr>
                (+53)7 267-7890
            </address>
            <address>
                <strong>Ing. Ignacio Hernández</strong><br>
                <a href="mailto:#">missoluciones22@yandex.com</a>
            </address>

        </div>
    </div>
</div>
{% endblock %}

templates/libros_confirm_delete.html
{% extends 'index.html' %}
{% block contenido %}
<div  style="height: 20px" class="jumbotron">
<div style="margin-left:auto;margin-right: auto;">
  <h5>Hola ¿en qué te podemos ayudar?</h5>
  <p>Vas borrar el Libro "{{ libros.titulo }}"</p>
 </div>
</div>
<form method="post">{% csrf_token %}
¿Estás seguro que deseas borrar la tarea "{{ libros.titulo }}"?
<input type="submit" value="Aceptar" />
</form>
{% endblock %}

templates/libros_form.html
{% extends 'index.html' %}
{% block contenido %}
<div  style="height: 20px" class="jumbotron">
<div style="margin-left:auto;margin-right: auto;">

  <p>Agregue nombre del libro del cual resolverá problemas</p>
 </div>
    </div>
<div class="mx-auto border" style="width: 900px;" >
<form  method="post">{% csrf_token %}

{{form.as_table}}

<input type="submit" value="Guardar" class="btn btn-primary"/>
</form>
     </div>
{% endblock  %}

templates/login.html
<!DOCTYPE html>
	{% load static %}
<html lang="en">
 <head>
{% load bootstrap4 %}
{% bootstrap_css %}
<title>MisSoluciones Auntentificate</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'descarga/ccs.css' %}" rel="stylesheet" type="text/css"  />
        <link href="{% static 'descarga/fuente.css' %}" rel="stylesheet" type="text/css"  />
        <link href="{% static 'fonts/sb-bistro/sb-bistro.css' %}" rel="stylesheet" type="text/css"  />
        <link href="{% static 'fonts/font-awesome/font-awesome.css' %}" rel="stylesheet" type="text/css"  />

        <link href="{% static 'packages/bootstrap/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"  />
        <link href="{% static 'packages/o2system-ui/o2system-ui.css' %}" rel="stylesheet" type="text/css" media="all"  />
        <link href="{% static 'packages/owl-carousel/owl-carousel.css' %}" rel="stylesheet" type="text/css" media="all"  />
        <link href="{% static 'packages/cloudzoom/cloudzoom.css' %}" rel="stylesheet" type="text/css" media="all"  />
        <link href="{% static 'packages/thumbelina/thumbelina.css' %}" rel="stylesheet" type="text/css" media="all"  />
        <link href="{% static 'packages/bootstrap-touchspin/bootstrap-touchspin.css' %}" rel="stylesheet" type="text/css" media="all"  />
        <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text/css" media="all"  />

</head>
<body>
	<div class="page-header">
		 <!--=============== Navbar ===============-->
		<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-transparent" id="page-navigation">
			<div class="container">
             <!-- Navbar Brand -->
             <a href="index.html" class="navbar-brand">
	        <img src="{% static 'img/logo/logo.png' %}" alt="">

            </a>
             <!-- Toggle Button -->
			 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
            </div> 
		</nav>
	</div>
	<div id="page-content" class="page-content">
        <div class="banner">
            <div class="jumbotron jumbotron-bg text-center rounded-0" style="background-image: url('{% static "img/logo/3862130.jpg" %}');">
							
                <div class="container">
                    <h1 class="pt-5">
                        Iniciar Sesión
                    </h1>
                    <p class="lead">
                       Un excelente colectivo puede ayudarlo a encontrar la solución
                    </p>
             {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


                    <div class="card card-login mb-5">
                        <div class="card-body">
                             <div style="color:#800080" id="demo"></div>
                            <ul class="messages">
                            <form class="form-horizontal" action="" method="post"> {% csrf_token %}
                                <div class="form-group row mt-3">
                                    <div class="col-md-12">
                                        <input id="username" onkeyup="letras(this.value)" class="form-control" type="text" required="" placeholder="Usuario" name="username">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input class="form-control" type="password" required="" placeholder="Contraseña" name="password">
                                    </div>
                                </div>
                               
                                <div class="form-group row text-center mt-4">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-primary btn-block text-uppercase">Acceder</button>
                                    </div>
                                </div>
								
                            </form>
							<div class="form-group row text-center mt-4">
								<div class="col-md-12">
									<a  href="{% url 'registro' %}" class="btn btn-primary btn-block text-uppercase">Registrarse</a>
									
								</div>
							</div>

							

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h5>Como encontrarnos</h5>
                    <p></p>
                </div>
                <div class="col-md-3">
                    <h5>Enlaces</h5>
                    <ul>
                        <li>
                            <a href="about.html">About</a>
                        </li>
                        <li>
                            <a href="contact.html">Contactanos</a>
                        </li>
                        
                        <li>
                            <a href="javascript:void(0)">Como trabajamos</a>
                        </li>
                        <li>
                            <a href="terms.html">Terminos</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="col-md-3">
                     <h5>Contact</h5>
                     <ul>
                         <li>
                            <a href="tel:+620892738334"><i class="fa fa-phone"></i> 08272367238</a>
                        </li>
                        <li>
                            <a href="mailto:hello@domain.com"><i class="fa fa-envelope"></i>soluciones23@gmail.com</a>
                         </li>
                     </ul>

                     <h5>Seguirnos</h5>
                     <ul class="social">
                         <li>
                            <a href="javascript:void(0)" target="_blank"><i class="fab fa-facebook-f"></i></a>
                         </li>
                         <li>
                            <a href="javascript:void(0)" target="_blank"><i class="fab fa-instagram"></i></a>
                         </li>
                         <li>
                            <a href="javascript:void(0)" target="_blank"><i class="fab fa-youtube"></i></a>
                         </li>
                     </ul>
                </div>
                <div class="col-md-3">
                     <h5>Descarga nuestra APP</h5>
                     <ul class="mb-0">
                         <li class="download-app">
                             <a href="#"><img src="{% static 'img/playstore.png' %}"></a>
							</li>
                         <li style="height: 200px">
                             <div class="mockup">
                                 <img src="{% static 'img/mockup.png' %}">
							 </div>
                         </li>
                     </ul>
                </div>
            </div>
        </div>
        <p class="copyright">&copy; 2022 MisSoluciones | Estudio Online. Derechos Reservados.</p>
    </footer>
<script>
	function letras(texto){
  var letras1=sonLetrasSolamente(texto)
  if (letras1==false){
  document.getElementById("demo").innerHTML = 'Son letras solamente' ;
  document.getElementById("username").value = '' ;
}
else{document.getElementById("demo").innerHTML = '' ;}
}
function sonLetrasSolamente(texto){
  var regex = /^[a-zA-Z]+$/;
  return regex.test(texto);
}
 </script>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-migrate.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/bootstrap/libraries/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/bootstrap/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/o2system-ui/o2system-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/owl-carousel/owl-carousel.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/cloudzoom/cloudzoom.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/thumbelina/thumbelina.js' %}"></script>
    <script type="text/javascript" src="{% static 'packages/bootstrap-touchspin/bootstrap-touchspin.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme.js' %}"></script>



</body>

templates/temas_form.html
{% extends 'index.html' %}
{% block contenido %}
<div  style="height: 20px" class="jumbotron">
<div style="margin-left:auto;margin-right: auto;">

  <p>Agregue el Tema del cual resolverá problemas</p>
 </div>
    </div>
<div class="mx-auto border" style="width: 900px;" >
<form  method="post">{% csrf_token %}

{{form.as_table}}


<input type="submit" value="Guardar" class="btn btn-primary"/>
</form>
     </div>
{% endblock  %}